version: "3.8"
services:
  jira-app:
    container_name: jira-app
    image: jira
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - jira-db
    env_file:
      - .env
    networks:
      - backend


  jira-db:
    image: postgres
    container_name: jira-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DB}
    networks:
      - backend


  nginx:
    container_name: nginx
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - backend
    depends_on:
      jira-app:
        condition: service_started

networks:
  backend:
    driver: bridge

